const types = {
  GO_TO_LOG_IN: 'GO_TO_LOG_IN',
  GO_TO_REGISTER: 'GO_TO_REGISTER',
  GO_TO_HOME: 'GO_TO_HOME',
  GO_TO_HELP: 'GO_TO_HELP',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  GET_REPOS: 'GET_REPOS',
  GO_TO_REPO: 'GO_TO_REPO'
}


export default types
